# Generated by Django 5.0.1 on 2024-02-29 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_book_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_image',
        ),
    ]
